### ISSUE TITLE
Question on PLW and PC

### ISSUE THREAD

**Issue by ooodragon94** [askforalfred/alfred#10]
I want the nomenclature to be clear.

so PLW (which is an acronym for path_len_weight in code?) that is given when running eval_seq2seq.py is equal to "Path Weighted Metrics" in the paper?

and I'm not quite sure what PC means (in the code it says postcondition but I don't see this word in the paper)

Anyone mind clarifying these terms out?

**Comment by MohitShridhar** [comment]
Yes, path_len_weight is "Path Weighted Metrics". Right, in the code we use "Post Conditions" to indicate "Goal Conditions" from the paper. Thanks for the pointers, we will update them soon to be consistent with the paper.
