### ISSUE TITLE
Data generation for new tasks described by PDDL

### ISSUE THREAD

**Issue by rutadesai** [askforalfred/alfred#102]
Hi there,

I am interested in using the code in gen folder (PDDL-based expert trajectory generation) for different tasks (e.g., make pizza + cookies) than the ones defined in the alfred paper. I can define these tasks using PDDL as well. Would this be possible? Would you be able to provide a brief description of your gen code including an entry point for the same? 

Thanks very much for your help!

**Comment by MohitShridhar** [comment]
@rutadesai, the simulator (THOR) used by ALFRED has a limited number of objects and interactions. I don't think pizzas and cookies are part of the environment, afaik. But if you are interested in using PDDL to solve general planning problem, then yes, PDDL is applicable. PDDL-based planning typically requires two things: (1) a symbolic description of states (2) a symbolic world model of how you can act in the environment. With this you can use something like FF to plan a sequence of actions to achieve a goal. Checkout this example: https://github.com/guillaume-chevalier/AI-Planning-Solver-Shakeys-World-PDDL

**Comment by rutadesai** [comment]
Thanks, @MohitShridhar! Sorry I wasn't clear. I am willing to add the necessary objects and actions in AI2Thor for my usecase. And I actually have the pddl domain file and solver working in python with a toy example. I am interested in integrating it in AI2Thor to get corresponding video data of these tasks. So, I was hoping to take advantage of your code for the same. I am wondering if this sounds doable with your gen code and if so what would be some entry points in the code for 1) adding new objects and actions correspond to a pddl domain file 2) changing the pddl solver (I need to use OPTIC solver instead of FF), and 3) way to visualize a single trajectory once I have done #1 and #2. 

Thanks very much again!
Ruta

**Comment by MohitShridhar** [comment]
Ah I see, thanks for clarifying. So assuming you have added your objects to THOR 2.1.0 [(this commit)](https://github.com/allenai/ai2thor/tree/5077c3dcaaa9622111b1f74e35801150c165339a) and recompiled the binaries with Unity, you can adapt the PDDL domain and problem descriptions to your tasks:
1. Modify the domain to reflect new actions [here](https://github.com/askforalfred/alfred/blob/master/gen/planner/domains/PutTaskExtended_domain.pddl).
2. Add a new list of goals to the [library](https://github.com/askforalfred/alfred/blob/master/gen/goal_library.py).
3. Use this [function](https://github.com/askforalfred/alfred/blob/master/gen/game_states/planned_game_state.py#L60) to convert THOR metadata into PDDL problem files.
4. Then use [generate_trajectories.py](https://github.com/askforalfred/alfred/tree/master/gen#generation) script to generate your new tasks. This should automatically show you THOR visualizations of agent executions.

Hope this helps!

**Comment by rutadesai** [comment]
thanks very much, @MohitShridhar!! This is exactly what I was looking for! :)
