### ISSUE TITLE
Error on monterey

### ISSUE THREAD

**Issue by ganjarpanji** [askforalfred/alfred#103]
just update from bigsur to monterey and unable to open alfred.app. i checked to launch the executable manually and displayed this error
![image](https://user-images.githubusercontent.com/1736817/141603156-3fb7a264-2dce-4488-9d43-e9307617ba3f.png)

**Comment by MohitShridhar** [comment]
Sorry, this is a research project repository named ALFRED. Not the OSX app Alfred.
