### ISSUE TITLE
How to generate position coordinates for the agent in each frame?

### ISSUE THREAD

**Issue by wang-sj16** [askforalfred/alfred#105]
Hi, I'm wondering how can I generate position coordinates for the agent in each frame and the position of target? Thanks!

**Comment by MohitShridhar** [comment]
@wang-sj16, use the metadata info from THOR: https://allenai.github.io/ai2thor-v2.1.0-documentation/event-metadata#agent 

But note that you can only use this info during training, not during val or test.
