### ISSUE TITLE
meaning of CoordinateObjectID

### ISSUE THREAD

**Issue by nikita-petrashen** [askforalfred/alfred#107]
Hi!
How to get which instance of Potato do we interact with from these numbers? 
![image](https://user-images.githubusercontent.com/49820557/157717272-dadbf88f-eca9-4eeb-a556-e7aaa49586a0.png)

Side question: in tasks like `pick_two_obj_and_place-PotatoSliced-None-GarbageCan-28` we need to slice two potatoes but in the original AI2-THOR [scene](https://github.com/allenai/ai2thor/blob/main/unity/Assets/Scenes/FloorPlan28_physics.unity) we have only one potato instanced, what's the deal with that?

Thank you!

**Comment by MohitShridhar** [comment]
@nikita-petrashen, 

> How to get which instance of Potato do we interact with from these numbers?
Use `objectID`. This string uniquely describes each object in the scene.

> Side question: in tasks like pick_two_obj_and_place-PotatoSliced-None-GarbageCan-28 we need to slice two potatoes but in the original AI2-THOR 
In THOR (not the Unity Editor) interactable objects are spawned whenever a scene is instantiated. If the task involves two potatoes, then there must be two potatoes in the scene because the expert was able to complete the task during data generation.

**Comment by MohitShridhar** [comment]
ohhh sorry... @thomason-jesse just pointed out that for 'slicing' tasks maybe just one potato is sufficient because after a `Slice` action the potato is split into several slices, after which the agent can pick up two slices from the same pile (one by one).

**Comment by nikita-petrashen** [comment]
The thing is, THOR API is not suitable for my purpose, so what I'm trying to do is to manipulate the scene in the form of a point cloud using my own toolkit, thus creating a series of scene states which represents ALFRED's agent action sequence.

Back to potatoes, I have an item `Potato_21b79aff` in my scene located somewhere, and would like to know how to build a correspondence between these items in the scene and `objectID`s in the trajectory descriptions.

Also, could you please hint the way how I can spawn several potatoes in the Unity itself? Maybe according to the `scene` part of the trajectory JSON? I cannot use THOR API for this because there is no way to get the point cloud representation of the scene from it, as was pointed in this [issue](https://github.com/allenai/ai2thor/issues/961).

Thanks!

**Comment by thomason-jesse** [comment]
That kind of AI2THOR manipulation is outside the scope of the ALFRED repository, but you might be able to get answers from the main [AI2THOR](https://github.com/allenai/ai2thor) repo. You could also check out the [LUMINOUS](https://github.com/amazon-research/indoor-scene-generation-eai/) framework for automatically generating new ALFRED-compatible scenes at the Unity level.
