### ISSUE TITLE
get object in the scene using `ObjectID`

### ISSUE THREAD

**Issue by nikita-petrashen** [askforalfred/alfred#108]
Hi! Sorry for repeating the same question, but I still have it after the closing of my previous [issue](https://github.com/askforalfred/alfred/issues/107).

In the answer you have mentioned that the `ObjectID` attribute uniquely defines the object in the scene. But how does it work exactly? The `ObjectID` string is quite different from object identifiers in original Unity scenes and I need to get the exact correspondence between the objects in the task and the assets in the scene.

Thanks for your patience!

**Comment by MohitShridhar** [comment]
@nikita-petrashen, just to be clear here: the ALFRED dataset is based on the Ai2THOR simulator, which is an executable binary that is interfaced through python. We basically treated this binary as a blackbox without know much about how it works underneath – including how `ObjectID`s are instantiated. So you will have to check here: https://github.com/allenai/ai2thor 

Thank you for understanding!

**Comment by nikita-petrashen** [comment]
Got it! Thanks.
