### ISSUE TITLE
postconditions_met for sliced objects

### ISSUE THREAD

**Issue by Tushar-N** [askforalfred/alfred#11]
In ALL tasks involving a sliced object, the postcondition check while checking task success is:

```
if 'Sliced' in targets['object']:
    ts += 1
    if 'Sliced' in [p['objectId'] for p in pickupables]:
        s += 1
```

For example in [L336](https://github.com/askforalfred/alfred/blob/master/env/tasks.py#L336) of `tasks.py`. Shouldn't these instances be 
```
if np.any(['Sliced' in p['objectId'] for p in pickupables]):
    s += 1
```

There are 145 of these in valid_seen, which almost matches what [this issue](https://github.com/askforalfred/alfred/issues/7) reports.

**Comment by MohitShridhar** [comment]
Thanks a lot for pointing this out @Tushar-N! I just pushed a fix to `master`. 

I re-ran the metrics for `tests_seen` and `tests_unseen`:
```
"tests_seen": {
    "results": {
        "path_length_weighted_postcondition_success_rate": 0.06558818686569017,
        "path_length_weighted_success_rate": 0.020214967618991903,
        "postcondition_success": {
            "completed_postconditions": 378,
            "postcondition_success_rate": 0.09521410579345088,
            "total_postconditions": 3970
        },
        "success": {
            "num_evals": 1533,
            "num_successes": 63,
            "success_rate": 0.0410958904109589
        }
    },
}
"tests_unseen": {
    "results": {
        "path_length_weighted_postcondition_success_rate": 0.048352258595222,
        "path_length_weighted_success_rate": 0.001378946369113455,
        "postcondition_success": {
            "completed_postconditions": 278,
            "postcondition_success_rate": 0.07489224137931035,
            "total_postconditions": 3712
        },
        "success": {
            "num_evals": 1529,
            "num_successes": 7,
            "success_rate": 0.004578155657292348
        }
    },

}
```

Looks like the numbers are slightly higher, but not substantially different to the ones reported in the paper. We will update the numbers in the Leaderboard and paper soon. 

Thanks again for spotting this! 👍

**Comment by MohitShridhar** [comment]
Leaderboard numbers have been [updated](https://leaderboard.allenai.org/alfred/submissions/public). Closing for now.
