### ISSUE TITLE
Default parameters for training and log files

### ISSUE THREAD

**Issue by Tushar-N** [askforalfred/alfred#12]
> Supervision. We train all models using the teacher-forcing paradigm on the expert trajectories, and this ensures the language directives match the visual inputs.

The paper has this bit about teacher forcing, but the training command in the Readme does not use the `--dec_teacher_forcing` flag. Is this needed to train the model?

Also would it be possible to share the log files (stdout and tensorboard logs) for the training run that resulted in the pretrained checkpoint?

**Comment by MohitShridhar** [comment]
Sorry, some of the terms used in the paper are not consistent with the code. We will fix them in the next update. `--dec_teacher_forcing` is not required.

The [pre-trained model folder](https://github.com/askforalfred/alfred/tree/master/models#pre-trained-model) contains a `config.json` with all the hyperparams and settings. Unfortunately, I don't have the log files for these models. But will post them when I re-run the experiments for the next update.
