### ISSUE TITLE
Not detecting microwave during data generation

### ISSUE THREAD

**Issue by RishiHazra** [askforalfred/alfred#121]
Hi,

I'm trying to generate data with new goal definitions. I've updated the code to work on the AI2Thor 4.2.0. While it's able to generate new data for goal pertaining to pick, place, clean and cool -- when it comes to heat sub-goal, it no longer works. While trying to narrow down the issue, I realized that self.env.last_event.metadata["objects"] (in [gen/game_states/task_game_state_full_knowledge.py](https://github.com/askforalfred/alfred/blob/1898b83547b589b8635737929e04ee4f2f404177/gen/game_states/task_game_state_full_knowledge.py#L40)) does not show "Microwave" even though it is present in the scene and in clear view. It can detect "StoveBurner" & "Fridge" though. 

As such the planner keeps failing with the error: 
```
ff: goal can simplified to FALSE. No plan will solve it
```
Any help is appreciated. Thanks !!!

**Comment by askforalfred** [comment]
Hey Rishi, that's exciting! I hope you're able to find a workaround, but we
feel that this particular issue is outside the scope of the maintenance of
the ALFRED codebase.

My gut feeling is "Microwave" might either be named something else in the
newer version in some (all?) scenes [fixable on your end] or the mesh isn't
named in the metadata in a particular scene [open issue on AI2-THOR repo if
you can confirm]. Good luck!

**Comment by RishiHazra** [comment]
Thanks for the quick response. I can confirm that Microwave hasn't been renamed in the new version of AI2Thor.

On digging further, I was able to trace it to the function in [alfred/env/thor_env.py](https://github.com/jiasenlu/alfred/blob/32a288fd072df3d6b9ce80a16c1efbbd6a7280f7/env/thor_env.py#L91)
```python
def restore_scene(self, object_poses, object_toggles, dirty_and_empty):
```
It seems like running this function with **action=SetObjectPoses** leads to the discarding of certain objects -- as in Microwave is detected initially in the list of objects in the event metadata (last_event.metadata["objects"]), however on running this function, it gets discarded. Moreover, it also discards objects like GarbageCan, Shelf, etc all of which are initially detected in the event metadata. This happens irrespective of the FloorPlan. I can see a couple of TODO marked there which sort of resembles my issue.

I've opened an issue on AI2Thor repo too.

**Comment by RishiHazra** [comment]
Update: I was able to figure out the error. By editing the [object_poses](https://github.com/jiasenlu/alfred/blob/32a288fd072df3d6b9ce80a16c1efbbd6a7280f7/gen/scripts/generate_trajectories.py#L551), to include 'moveable' objects as well as 'pickupable' objects, I was able to resolve the issue. Apparently, objects like Microwave, CoffeeMachine, GarbageCan, etc. have **moveable=True** property and while performing the action='SetObjectPoses', AI2Thor drops all objects that aren't moveable or pickupable ([see documentation](https://ai2thor.allenai.org/ithor/documentation/objects/set-object-states/))

```python
object_poses = [{'objectName': obj['name'].split('(Clone)')[0],
                                        'position': obj['position'],
                                        'rotation': obj['rotation']}
                                        for obj in env.last_event.metadata['objects'] if obj['pickupable'] or obj['moveable']]
```

Going ahead and closing the issue.
