### ISSUE TITLE
What is the format of the action masks in the original json file?

### ISSUE THREAD

**Issue by wzcai99** [askforalfred/alfred#127]
After downloading the full_dataset, I extract the trajectory JSON files and try to figure out how to restore the original 300x300 image masks for actions. I noticed that in the preprocess.py file, a notation is listed that "The masks need to be decompressed". So could you please tell me how to decompress the action masks? Thank you.

**Comment by wzcai99** [comment]
In the original JSON files, the action masks seems to be a (36x2) matrix and contains large values.

**Comment by MohitShridhar** [comment]
@wzcai99, see [this](https://github.com/askforalfred/alfred/blob/f2de579cdc812f8adf3ce4999f4eb6fb45339c0e/gen/utils/image_util.py#L24) for `decompress_mask`. Example usage [here](https://github.com/askforalfred/alfred/blob/f2de579cdc812f8adf3ce4999f4eb6fb45339c0e/gen/utils/replay_json.py#L42)

**Comment by wzcai99** [comment]
Thank you very much. I close this issue.
