### ISSUE TITLE
Question about Resnet-18 to encode vision info in Alfred benchmark

### ISSUE THREAD

**Issue by WhyTheMoon** [askforalfred/alfred#129]
Hello, may I ask what is the training set used for the resnet-18 used to encode visual scenes in the Alfred dataset?
![image](https://user-images.githubusercontent.com/107178692/210702243-0a93e7a9-87e0-4437-8180-39ab4c224c80.png)

**Comment by MohitShridhar** [comment]
@WhyTheMoon, it's just a standard ResNet-18 from PyTorch pre-trained on ImageNet. See this [script](https://github.com/askforalfred/alfred/blob/f2de579cdc812f8adf3ce4999f4eb6fb45339c0e/models/utils/extract_resnet.py#L29) for details.
