### ISSUE TITLE
Accessing frames in batches and selecting section of Natural language instruction for the input to the model.forward() function.

### ISSUE THREAD

**Issue by Alrick11** [askforalfred/alfred#13]
I had one question and a clarification regarding the code.

Question 1. We get frames (images), only when we interact with the environment, because the action we choose decides the frame we receive, but you seem to be loading the frames from the dataset. How can I know the frames before hand without executing my model output action in the environment?

Clarification: You mask your padded NL instructions using DotAttn() function (where in you multiply the language instruction with the previous hidden states), and then submit it as an input to your model.forward(). Is this a correct interpretation of how you decide which part of the language instruction is to be used for the next iteration?

Thanks

**Comment by MohitShridhar** [comment]
1. So the Seq2Seq models are trained offline with dataset images, but evaluated online with the simulator. The training objective is to imitate the actions taking by the expert. If you need real-time feedback from actions (e.g. typical RL setting), then you need to [run the simulator](https://github.com/askforalfred/alfred/blob/master/models/eval/eval_task.py#L63).

2. This [part](https://github.com/askforalfred/alfred/blob/1c9e83233f36c1629c07659528f022dfb01b1456/models/nn/vnn.py#L140) handles language attention. DotAttn computes a weighted sum of language encodings. This weighted sum is then [concatenated](https://github.com/askforalfred/alfred/blob/1c9e83233f36c1629c07659528f022dfb01b1456/models/nn/vnn.py#L143) with the vision and previous action embeddings.

**Comment by Alrick11** [comment]
Thank you for the clarification!

Best

**Comment by Alrick11** [comment]
Hi,

I know the topic is closed but how did you generate the offline dataset
images?

Best

Alrick Dsouza
Grad student at UW
Contact: +1-206-902-7962
Facebook <https://www.facebook.com/alrick.dsouza> | Linkedin
<http://linkedin.com/in/alrick-dsouza-170743113>

**Comment by MohitShridhar** [comment]
We used a PDDL-based planner to generate expert demonstrations, and then executed them in the THOR simulator. Images were saved after taking each action in the demonstration.

Please refer to the [paper](https://arxiv.org/pdf/1912.01734.pdf) for more details.

**Comment by Alrick11** [comment]
Thank you!!
