### ISSUE TITLE
Inquiry Regarding the Leaderboard

### ISSUE THREAD

**Issue by SeungyounShin** [askforalfred/alfred#133]
I am curious to know whether the test server is capable of recognizing 
attributes such as color, heated, cooled, etc. or 
relations such as in front of, by, behind, etc. 

for unseen tasks like "Place {} on the `silver-colored` cabinet" or "Place it `in front of` the coffeemaker"~~
'Place `heated` tomato on the table'
Is recognized?

**Comment by thomason-jesse** [comment]
See the paper for full details, but the upshot is "no" for most of these properties. Whether an object has been heated or cooled is checked; those properties are required for several ALFRED tasks. However, spatial information is limited to `in/on` relationships (e.g., egg in bowl; bowl on count). Colors and relative orientation relations (e.g., "front") are not checked against.
