### ISSUE TITLE
What is the best way to get a GT mask?

### ISSUE THREAD

**Issue by TopCoder2K** [askforalfred/alfred#134]
Do I understand correctly that `env.last_event.class_masks` contains gt masks for all objects present in `self.env.last_event.frame`? 
How to pick the desired gt mask? Is that correct:
```
class2mask = self.env.last_event.class_masks
mask = class2mask[target_obj]
```
where `target_obj` is the name of the target class (i.e. without any additional info like coordinates and so on, e.g. 'KeyChain')?

**Comment by MohitShridhar** [comment]
@TopCoder2K check out the `augment_trajectories.py` [guide](https://github.com/askforalfred/alfred/tree/master/gen#data-augmentation). GT masks are saved [here] (https://github.com/askforalfred/alfred/blob/master/gen/scripts/augment_trajectories.py#L68).

**Comment by TopCoder2K** [comment]
@MohitShridhar, thank you for the links! But are you sure this is the best way of obtaining masks when you only have a class name (I'm trying to build a GT segmentator that returns a GT mask by class name)? 
I've seen the use of `last_event.instance_segmentation_frame` and `last_event.color_to_object_id` inside the `ThorEnv.va_interact()` function but it looks like a different scenario. Also, I've noticed that there are keys like `'CellPhone|+02.71|+00.80|-01.48'` and `'CellPhone'` inside `last_event.object_id_to_color`, so I'm not sure which one I should choose when I only have 'CellPhone' as a target class.

**Comment by TopCoder2K** [comment]
Interesting... 
For this frame 
![193](https://user-images.githubusercontent.com/47208659/217312674-f3d5b9bf-039a-4575-9ec6-387588bc06e5.png)
`env.last_event.class_masks` keys are 
```
['Cube.175', 'Cabinet', 'OVENDOORBOTTOM.002', 'Drawer', 'Knife', 'CounterTop', 'Spatula', 'Sink', 'Cup', 'Apple', 'Bottle', 'Sphere.014', 'Jar', 'Bag', 'Faucet', 'Cube.003', 'Ladle']
```
so, there is no `'AppleSliced'` while `env.last_event.color_to_object_id` has four objects containing 'AppleSliced' in their names:
```
(4, 13, 230): 'Apple|-01.27|+00.85|+00.23|AppleSliced_2'
(93, 226, 181): 'AppleSliced'
(95, 55, 227): 'Apple|-01.27|+00.85|+00.23|AppleSliced_1'
(245, 235, 43): 'Apple|-01.27|+00.85|+00.23|AppleSliced_0'
```
Thus, the second question above remains: can I choose any object containing 'AppleSliced' and be sure that the interaction will be successful (in case the target object close enough)?

**Comment by TopCoder2K** [comment]
I also do not understand how does interaction work. Looking at `ThorEnv.va_interact()`, one may think that the correct mask is enough for successful interaction, but I've encountered such cases:
![157](https://user-images.githubusercontent.com/47208659/217511096-8c03bb1b-780c-4e51-8606-5bfdfd697c24.png)
![gt_mask_157](https://user-images.githubusercontent.com/47208659/217508670-62379502-7879-4e14-a54c-424a61b0cf10.png)
```
Action is OpenObject, Success is False, Object failed to open/close successfully.
```
![213](https://user-images.githubusercontent.com/47208659/217508856-10c64635-f02d-4743-9a04-5f5b2ab99d1c.png)
![gt_mask_213](https://user-images.githubusercontent.com/47208659/217508870-185ad987-dc80-4699-98ca-49d69dc2bf55.png)
```
Action is PickupObject, Success is False, (without any error).
```

I could explain the second case with something like: 'More than half of the object is not visible, why do you expect the interaction to be successful?', but why wasn't the fridge opened???

**Comment by TopCoder2K** [comment]
It's the same puzzlement here:
![41](https://user-images.githubusercontent.com/47208659/218440831-0c63230b-cee5-46c8-972f-0682784ef779.png)
![gt_mask_41](https://user-images.githubusercontent.com/47208659/218440823-a6e71cb4-69c5-4083-9106-b110e1c09e2b.png)
```
Action is PutObject, Success is False, No valid positions to place object found.
```
although the object is visible. Why has it not been successful?

**Comment by thomason-jesse** [comment]
The error message from AI2THOR details the reason: "No valid positions to place object found." This version of THOR samples potential locations for the held object against the receptacle and fails if it iterates through them and finds that they all cause collisions. It can be resolved by trying again from a different position (sometimes) or by clearing off whatever is already on the receptacle.

Similarly the error "Object failed to open/close successfully." is the reason for the fridge open/close. This error is most common when the agent is standing close enough that the fridge door would collide with it or with its held object on the path to opening.

In both cases, these are simulator quirks at the AI2THOR level, and the error messages you copied over are the explanations. These aren't ALFRED-specific problems.

**Comment by TopCoder2K** [comment]
@thomason-jesse, thank you for the explanations! They are really valuable because I've seen the error messages, but the reason behind them remained unclear. In addition, it's quite surprising to me that there are cases similar to what happened with the "ArmChair". I thought AI2THOR didn't have any quirks...
