### ISSUE TITLE
Can't validate a model in Test dataset.

### ISSUE THREAD

**Issue by bhkim94** [askforalfred/alfred#14]
First of all, thank you for the awesome code.

I'm trying to validate a model after traininig.
Validation dataset for both seen and unseen works great, but Test dataset returns errors for both seen and unseen cases.
Here's the error message.

> tests_seen': 1533,
>  'tests_unseen': 1529,
>  'train': 21023,
>  'valid_seen': 820,
>  'valid_unseen': 821}
>  ...
> ThorEnv started.
> Evaluating: data/json_feat_2.1.0/trial_T20190909_042500_949430
> No. of trajectories left: 1532
> Resetting ThorEnv
> Task: Retrieve the sponge from the kitchen island, place in fry pan, put fry pan on kitchen island.
> Traceback (most recent call last):
>   File "/home/user/Desktop/alfred/models/eval/eval_task.py", line 34, in run
>     cls.evaluate(env, model, r_idx, resnet, traj, args, lock, successes, failures, results)
>   File "/home/user/Desktop/alfred/models/eval/eval_task.py", line 51, in evaluate
>     cls.setup_scene(env, traj_data, r_idx, args, reward_type=reward_type)
>   File "/home/user/Desktop/alfred/models/eval/eval.py", line 120, in setup_scene
>     env.set_task(traj_data, args, reward_type=reward_type)
>   File "/home/user/Desktop/alfred/env/thor_env.py", line 122, in set_task
>     task_type = traj['task_type']
> KeyError: 'task_type'
> Error: KeyError('task_type',)
>  ...

And redownloading json_feat_2.1.0 didn't help.

How can I solve it?

Again, thanks for sharing the great code.

**Comment by MohitShridhar** [comment]
The expert demonstrations for `test_seen` and `test_unseen` are not open to the public. This is a standard practice to prevent someone from cheating with ground-truth actions on test scenes.

To evaluate your model on `test_seen` and `test_unseen`, see [leaderboard submission](https://github.com/askforalfred/alfred/tree/master/models#leaderboard) instructions.
