### ISSUE TITLE
Position Distribution of Each Object

### ISSUE THREAD

**Issue by yuchen-x** [askforalfred/alfred#140]
I was wondering what the position distribution of each object over possible locations was, where line of the code was regarding this. 

For each object, can it appear any where, or it only could be in a subset of receptacles? 
Thank you!

**Comment by MohitShridhar** [comment]
@yuchen-x, I vaguely remember looking at something like this a long time ago.

In [ALFWorld](https://github.com/alfworld/alfworld), I had a [list of potential objects](https://github.com/alfworld/alfworld/blob/master/alfworld/gen/constants.py#L553) that each receptacle could hold. But you probably need to sample random scenes to get an accurate distribution.
