### ISSUE TITLE
dataset reading problem

### ISSUE THREAD

**Issue by Deaddawn** [askforalfred/alfred#142]
Hi, there. I'm following the leaderboard instruction to run the demo. But I got the below error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/json_feat_2.1.0/trial_T20190908_033338_761740/pp/ann_1.json'
Error: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/murphy/workspace/alfred/models/eval/leaderboard.py", line 40, in run
    traj = model.load_task_json(task)
  File "/home/murphy/workspace/alfred/models/model/seq2seq.py", line 271, in load_task_json
    with open(json_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/json_feat_2.1.0/trial_T20190908_033338_761740/pp/ann_2.json'

It seems the data source(json_feat) structure has been altered. Can you check and give me a feedback?

**Comment by MohitShridhar** [comment]
@Deaddawn, it looks like the data was not preprocessed. Did you run with `--preprocess` (see [quickstart](https://github.com/askforalfred/alfred/tree/master/models#training))?

**Comment by Deaddawn** [comment]
> @Deaddawn, it looks like the data was not preprocessed. Did you run with `--preprocess` (see [quickstart](https://github.com/askforalfred/alfred/tree/master/models#training))?

thank you, all solved. BTW, is there a way I can slow down the speed of playing when running leaderboard.py?

**Comment by Deaddawn** [comment]
> > @Deaddawn, it looks like the data was not preprocessed. Did you run with `--preprocess` (see [quickstart](https://github.com/askforalfred/alfred/tree/master/models#training))?
> 
> thank you, all solved. BTW, is there a way I can slow down the speed of playing when running leaderboard.py?

Never Mind, adding time.sleep to solve.
