### ISSUE TITLE
RAM Issue

### ISSUE THREAD

**Issue by rishabhmathur99** [askforalfred/alfred#17]
HI, just to clarify is the quick-start training method loading the entire data-set into RAM. If this is the case, how would you suggest I run it if I have insufficient RAM?

**Comment by MohitShridhar** [comment]
Actually the `--preprocess` option should save preprocessed metadata into JSON files. The ResNet features are also loaded dynamically from the dataloader. So overall, the training shouldn't consume too much RAM. 

But if you are referring to GPU memory, you can try a smaller batch size.

**Comment by MohitShridhar** [comment]
Closing for now.
