### ISSUE TITLE
Why does `feat_conv.pt` has 10 more frames than the number of images?

### ISSUE THREAD

**Issue by TheShadow29** [askforalfred/alfred#21]
Hi. Thanks for the amazing repository.

I find that `feat_conv.pt` has 10 more frames than the image. For example, 

for `task=pick_cool_then_place_in_recep-LettuceSliced-None-DiningTable-17/trial_T20190909_070538_437648`, there are 455 images in `traj_data['images']`, but feat_conv is of shape 465x512x7x7

Similarly for `task=pick_two_obj_and_place-Newspaper-None-GarbageCan-218/trial_T20190907_225356_202464`, there are 530 images in `traj_data['images']` but feat_conv is of shape 540x512x7x7

Is there any particular reason why this is the case?

**Comment by MohitShridhar** [comment]
Hi @TheShadow29,

During data generation, we saved additional frames (interpolated with tiny increments) between commands like `MoveAhead`, `RotateRight`, `ToggleObjectOn` etc. to generate smooth videos. But we didn't end up using these frames in the model. Feel free to use them if they help!

**Comment by TheShadow29** [comment]
@MohitShridhar so is there some correspondence between such frames? For instance, if I wanted to use features for image_10, would that refer to the `feat_conv[9, ...]` or is there any other kind of mapping?

**Comment by MohitShridhar** [comment]
The `images` key in `traj_data.json` has a `low_idx`, `high_idx` and `image_name` (filename) for each image frame.

**Comment by TheShadow29** [comment]
@MohitShridhar so if I understand correctly: 

Using this low_idx and high_idx we can get which images correspond to the `low_actions` and `high_pddl`. That is, if a particular entry in `traj_data['images']` looks like:
`{'image_name': 000000020.png, 'high_idx': 0, 'low_idx': 5}`

then this image_20 corresponds to `traj_data['plan']['low_actions'][5]` and `traj_data['plan']['high_pddl'][0]`

Is the above correct?

I was looking through the code here https://github.com/askforalfred/alfred/blob/master/models/model/seq2seq_im_mask.py#L107
and it seems the enumeration is over `ex['images']` and the retrieved feature is `im[i]`. 
Does that mean the feature for image_20 is stored in `feat_conv[20]`? If so, how is the offset of 10 being taken care of?

Thank you for your patience.

**Comment by MohitShridhar** [comment]
Yep, that correct.

The loader only uses one image per low action, which happens [here](https://github.com/askforalfred/alfred/blob/master/models/model/seq2seq_im_mask.py#L111)

**Comment by TheShadow29** [comment]
@MohitShridhar thanks for confirming the first part. 

For the second part, yes, the loader uses one image per action, however, I was asking about the correspondence of this image (`ex['images']` in the code) with that of the feature_conv (`im` in the code). For instance,
`len(ex['images']) != len(im)` right? The code seems to use direct enumeration which would imply 

```
feat_conv[0: len(ex['images'])] = ResNet18_features(Image.open(ex['images'])
feat_conv[len(ex['images']: len(ex['images']+10] = Extra Features?
```

Does the question make sense? I could be misunderstanding your point.

**Comment by MohitShridhar** [comment]
Ah sorry, thanks for clarifying. 

The extra 10 in the end is just the last frame repeated 10 times. Sorry about this, this is some cruft left over from the generation phase. At the end of each generated trajectory, we saved 10 copies of the last frame, which was run through the feature extractor. But looks like `images` didn't get updated. Thanks for pointing this out.

**Comment by TheShadow29** [comment]
Awesome, thanks for clarifying and additional pointers. Closing this issue now.
