### ISSUE TITLE
Does a low-level instruction correspond to a PDDL action?

### ISSUE THREAD

**Issue by bhkim94** [askforalfred/alfred#22]
Hi,
First of all, really really huge thanks for consistent replying.

I've found instructions in some json files (for both training (ann.json) and validation (trad_data.json)) align to sub-goals as below. Is it true that the alignment holds for all trajectories in ALFRED?

```
Sub-goals in ("high_pddl" in "plan")
subgoals = {"GotoLocation", "PickupObject", "GotoLocation", "ToggleObject", "NoOp"}

Instructions in ("high_descs" in "turk_annotations")
instructions = {"go to ~~~", "pick up ~~~", "take something to somewhere", "turn on ~~~"}
```

In other words, I wonder if it's possible to figure out which sub-goal each instruction belongs to using the same index for all trajectories in ALFRED.
```
if subgoals[i] == "GotoLocation":
    instructions[i] is a "Goto" task. (should be)
else
    instructions[i] is an interaction task. (should be)
```

Again, huge thanks!

**Comment by MohitShridhar** [comment]
Yep! The step-by-step instructions are aligned with the subgoals. If you end up using this alignment for your model, please indicate so in your leaderboard submission as stated in the [guidelines](https://leaderboard.allenai.org/alfred/submissions/get-started).
