### ISSUE TITLE
Unable to find X server when running evaluation

### ISSUE THREAD

**Issue by shanestorks** [askforalfred/alfred#29]
Hello, I'm trying to evaluate the pre-trained model weights (which I have downloaded) using the steps on the readme within the models directory. The cloned repo resides on an AWS EC2 instance with Ubuntu 18.04 and Nvidia GPU. I have tried running the evaluation code via XQuartz terminal with X11 forwarding, and via the local terminal in an RDP (enabled through xRDP). After activating my conda environment which contains the dependencies and cd-ing to $ALFRED_ROOT (i.e., top-level directory of repo), my command is as follows:

`python models/eval/eval_seq2seq.py --model_path models/pretrained/model:seq2seq_im_mask,name:base30_pm010_sg010_01/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 4`

In both setups, when running the command, I'm getting the following error (one for each thread I'm trying to start, and also in single-thread case):

`No protocol specified
xdpyinfo:  unable to open display ":0".
Process Process-5:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/alfredPy/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/alfredPy/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/alfred/models/eval/eval_task.py", line 20, in run
    env = ThorEnv()
  File "/home/ubuntu/alfred/env/thor_env.py", line 34, in __init__
    player_screen_width=player_screen_width)
  File "/home/ubuntu/anaconda3/envs/alfredPy/lib/python3.6/site-packages/ai2thor/controller.py", line 855, in start
    self.check_x_display(env['DISPLAY'])
  File "/home/ubuntu/anaconda3/envs/alfredPy/lib/python3.6/site-packages/ai2thor/controller.py", line 715, in check_x_display
    ("Invalid DISPLAY %s - cannot find X server with xdpyinfo" % x_display)
AssertionError: Invalid DISPLAY :0 - cannot find X server with xdpyinfo`

I'm a novice in this area, but it seems (in my limited understanding) that the Thor component of this code can't access the X server to do some GUI rendering, e.g., of the simulated images during evaluation. However, in both setups, I can verify that the $DISPLAY variable is populated with something reasonable, e.g., "localhost:10.0" on XQuartz, and ":13.0" on RDP. I can also successfully run "xclock" and "xeyes" in both setups.

FYI, I am able to successfully begin training a new model from scratch, so it seems the dependencies, etc. are set up correctly.

I've been struggling with this problem for about a day now and haven't found much useful information online for it, so any information or insight is appreciated! Thank you!

**Comment by MohitShridhar** [comment]
Hi @shanestorks, thanks for your interest!

Forwarding this from @ekolve:

Running on headless AWS machines is possible, the main requirement is that you use a GPU machine to support OpenGL rendering.  I have attached a script 'startx.py', which examines the GPU devices on the host, generates a xorg.conf file and then starts X.  You can then run ai2thor as you normally would.  By default, the :0.0 display will be used, but if you are running on a machine with more than one GPU, you can address these by modifying the screen component of the display.  So :0.0 refers to the first device, :0.1 the second and so on.

startx.py
```
#!/usr/bin/env python


import subprocess
import shlex
import re
import platform
import tempfile
import os
import sys

def pci_records():
    records = []
    command = shlex.split('lspci -vmm')
    output = subprocess.check_output(command).decode()

    for devices in output.strip().split("\n\n"):
        record = {}
        records.append(record)
        for row in devices.split("\n"):
            key, value = row.split("\t")
            record[key.split(':')[0]] = value

    return records

def generate_xorg_conf(devices):
    xorg_conf = []

    device_section = """
Section "Device"
    Identifier     "Device{device_id}"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BusID          "{bus_id}"
EndSection
"""
    server_layout_section = """
Section "ServerLayout"
    Identifier     "Layout0"
    {screen_records}
EndSection
"""
    screen_section = """
Section "Screen"
    Identifier     "Screen{screen_id}"
    Device         "Device{device_id}"
    DefaultDepth    24
    Option         "AllowEmptyInitialConfiguration" "True"
    SubSection     "Display"
        Depth       24
        Virtual 1024 768
    EndSubSection
EndSection
"""
    screen_records = []
    for i, bus_id in enumerate(devices):
        xorg_conf.append(device_section.format(device_id=i, bus_id=bus_id))
        xorg_conf.append(screen_section.format(device_id=i, screen_id=i))
        screen_records.append('Screen {screen_id} "Screen{screen_id}" 0 0'.format(screen_id=i))
    
    xorg_conf.append(server_layout_section.format(screen_records="\n    ".join(screen_records)))

    output =  "\n".join(xorg_conf)
    print(output)
    return output

def startx(display):
    if platform.system() != 'Linux':
        raise Exception("Can only run startx on linux")

    devices = []
    for r in pci_records():
        if r.get('Vendor', '') == 'NVIDIA Corporation'\
                and r['Class'] in ['VGA compatible controller', '3D controller']:
            bus_id = 'PCI:' + ':'.join(map(lambda x: str(int(x, 16)), re.split(r'[:\.]', r['Slot'])))
            devices.append(bus_id)

    if not devices:
        raise Exception("no nvidia cards found")

    try:
        fd, path = tempfile.mkstemp()
        with open(path, "w") as f:
            f.write(generate_xorg_conf(devices))
        command = shlex.split("Xorg -noreset +extension GLX +extension RANDR +extension RENDER -config %s :%s" % (path, display))
        subprocess.call(command)
    finally: 
        os.close(fd)
        os.unlink(path)


if __name__ == '__main__':
    display = 0
    if len(sys.argv) > 1:
        display = int(sys.argv[1])
    print("Starting X on DISPLAY=:%s" % display)
    startx(display)
```

**Comment by shanestorks** [comment]
Hi Mohit,

Thanks for your help! This did the trick. 

For some reason I had to specify 1 as the display to startx.py and reconfigure the display Thor uses to :1 in gen/constants.py. Perhaps because I have my EC2 instance enabled for xRDP and it always has some Xorg processes running on :0.

I could be totally wrong there, but nonetheless, thank you for your help, and for providing this great resource to the community!

Best,
Shane

**Comment by 707346129** [comment]
Hi @MohitShridhar. I ran the code alfred/gen/scripts/generate_trajectories.py on the server and ran into the similar error. The server is not connected to any display. Is there anyway to run the data generation script without display?

**Comment by 707346129** [comment]
I ran the startx.py, and it shows "/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server".

**Comment by MohitShridhar** [comment]
For running on a headless server, see: https://github.com/askforalfred/alfred#cloud-instance 


>  "/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server".   

This seems like a permissions issue. Have you looked at this:
https://unix.stackexchange.com/questions/437809/start-x-server-on-login-with-systemd
