### ISSUE TITLE
AI2-THOR 2.4.0

### ISSUE THREAD

**Issue by danfeiX** [askforalfred/alfred#30]
Hi there,

Thanks for the great work! Is there any plan to make this repo compatible with the newest AI2-THOR release? Thanks!

**Comment by MohitShridhar** [comment]
Hi @danfeiX, thanks for your interest!

We don't have any immediate plans to upgrade to 2.4.0, but we could take a look at it some time later. This would involve updating some API calls, and getting the scene randomization to be consistent. Apparently, some static objects were moved around in 2.4.0, and the scene initialization is a bit different. So it might take some effort to ensure that the scenes are equivalent to the ones used for the data collection.

**Comment by MohitShridhar** [comment]
You can also take a look at the [release notes](https://github.com/allenai/ai2thor/blob/master/doc/static/ReleaseNotes/ReleaseNotes_2.4.md) for 2.4.0, to check if it's worth the upgrade.

The major changes are pull/pushable chairs with some additional objects.

**Comment by MohitShridhar** [comment]
Closing for now.
