### ISSUE TITLE
Should delete the first argument

### ISSUE THREAD

**Issue by Chucooleg** [askforalfred/alfred#31]
Should delete the first argument `task_type_ind` here
https://github.com/askforalfred/alfred/blob/bad0d71c3a83b982bf414ea866d2a0844ba80fbe/gen/utils/game_util.py#L337

Otherwise, it causes the inputs to be incorrectly shifted here
https://github.com/askforalfred/alfred/blob/bad0d71c3a83b982bf414ea866d2a0844ba80fbe/gen/game_states/task_game_state.py#L26

Which will cause an error if the task type is to examine in light
https://github.com/askforalfred/alfred/blob/bad0d71c3a83b982bf414ea866d2a0844ba80fbe/gen/game_states/task_game_state.py#L283
Error is raised here because None type cannot convert to int
https://github.com/askforalfred/alfred/blob/bad0d71c3a83b982bf414ea866d2a0844ba80fbe/gen/utils/game_util.py#L342

**Comment by MohitShridhar** [comment]
Fixed.
