### ISSUE TITLE
First Time Cloud User Questions

### ISSUE THREAD

**Issue by SouLeo** [askforalfred/alfred#34]
Hello!

I decided to post here instead of emailing just in case there are other first time cloud users out there who also need some guidance. 

I saw this link: [How to RunAI2 Simulation with GCP](https://medium.com/@etendue2013/how-to-run-ai2-thor-simulation-fast-with-google-cloud-platform-gcp-c9fcde213a4a) in the Repo Description, and I was curious if the specifications they provided:

>    2 Tesla K80 GPU with a 12GB graphics memory
>    16 vCores CPU
>    40–50 GB storage
>    Image of Intel® optimized Deep Learning Image: Base m24 (with Intel® MKL and CUDA 10.0)

were the same used by you all. I was also wondering, as a student, how much running on GCP might have cost you all.

Alternatively, if you all didn't use a cloud service, what hardware did you use? I have a 1080 8GB NVIDIA graphics card, and I ran into issue with not enough GPU RAM. I'm sort of stumped on whether or not I should get better hardware or pay for hourly usage of GCP or AWS

**Comment by MohitShridhar** [comment]
Hi @SouLeo 

We didn't use any GCP or AWS instances at all. We mostly used local GPU machines in our lab. Your 1080 card should be good enough; just try a smaller batch size. Training will be slow, but GCP/AWS might be worth it only after you are done prototyping and want to run large scale experiments.

**Comment by SouLeo** [comment]
Thank you for the advice! I lowered my batch size to 4, and it's chugging along fine now. :)
