### ISSUE TITLE
Get stuck when eval

### ISSUE THREAD

**Issue by cwhao98** [askforalfred/alfred#35]
When I eval the checkpoint, the process seems to be stuck during the initialization of the simulation environment.

>Loading:  exp/model:seq2seq_im_mask,name:pm_and_subgoals_01/best_unseen.pth
Found path: /home/ubuntu/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/ubuntu/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/ubuntu/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Logging to /home/ubuntu/.config/unity3d/Allen Institute for Artificial ### Intelligence/AI2-Thor/Player.log

Is there something wrong with the ai2thor?
Also, Is UI required？
Thanks.

**Comment by MohitShridhar** [comment]
@cwhao98 are you running on a headless machine without a display? Have you seen [this guide](https://github.com/askforalfred/alfred#cloud-instance)? 

You don't need a display, but you do need to configure X as explained in the guide.

**Comment by cwhao98** [comment]
@MohitShridhar 
Thanks for your replying.

Yes, I'm running on a headless machine without a display and I neglect the guide `startx.py`.

Now the problem is solved.

Thanks a lot.
