### ISSUE TITLE
Visual Angle

### ISSUE THREAD

**Issue by cwhao98** [askforalfred/alfred#36]
Hi.
At the beginning, is the visual angle of agent horizontal?
And does the environment provide an API to get some information about visual angle and coordinates?

**Comment by MohitShridhar** [comment]
@cwhao98 the agent starts off looking 30deg below the horizon.

Yes, see [this](https://ai2thor.allenai.org/ithor/documentation/metadata/#agent-attributes-). `event.metadata['agent']` should have the camera horizon.

**Comment by cwhao98** [comment]
@MohitShridhar  
Oh ! ! ! Thanks a lot.
