### ISSUE TITLE
 Data Generation

### ISSUE THREAD

**Issue by cwhao98** [askforalfred/alfred#37]
Hi, 
Could you please explain how the training data is generated？

Particularly, how is the 'action' generated？

I would appreciate it if you can provide some details.

**Comment by thomason-jesse** [comment]
Hi Wenhao, please check out the README in the "gen/" subdirectory. This covers basic data generation and augmentation.https://github.com/askforalfred/alfred/tree/master/gen

If you're interested in seeing how plan files are generated and the planner is invoked the get an action at each timestep, check out the scripts referenced specifically in this subsection:
https://github.com/askforalfred/alfred/tree/master/gen#generation
