### ISSUE TITLE
Parsing out w.r.t task type

### ISSUE THREAD

**Issue by aditya30887** [askforalfred/alfred#38]
Hello, 

The ALFRED paper mentions 7 task types. Is there a way to identify all the trial_data.json files corresponding to just one of these task types? for example - If I am only interested in the JSON files corresponding to pick and place across all floorplans then is there a task type tag associated with each trial_data.json file? Thank you for your help!

Regards, 
Adi

**Comment by MohitShridhar** [comment]
Hi Adi,

Yes. So [data/splits/oct21.json](https://github.com/askforalfred/alfred/blob/master/data/splits/oct21.json) has a list of trajectories sorted according to train/val/test splits. For train and val-seen/val-unseen trajectories, the `task` name contains the task-type, e.g `pick_cool_then_place_in_recep`. 

Also each `traj_data.json` file has a `task_type` key. See [this](https://github.com/askforalfred/alfred/tree/master/data#json-structure).

**Comment by aditya30887** [comment]
Thank you for your reply. Should have known better! I will close this now. 

Best, 
Adi
