### ISSUE TITLE
Leaderboard submission

### ISSUE THREAD

**Issue by muqiaoy** [askforalfred/alfred#39]
Hello,

I am assuming the file which should be submitted is tests_actseqs_dump_{datetime}.json. When I submit the file to the leaderboard, the test status is succeeded but the numbers do not show up. May I ask if this is because my .json file is in the wrong format?

Thanks so much!

Best,
Muqiao
![Screen Shot 2020-07-21 at 11 56 49 PM](https://user-images.githubusercontent.com/35796838/88132718-4a542d00-cbae-11ea-959d-ed3fec3f728c.png)

**Comment by MohitShridhar** [comment]
Did you click Publish? I think you might have to publish the results to view them. You can delete it later.

**Comment by MohitShridhar** [comment]
@muqiaoy is this yours?
![image](https://user-images.githubusercontent.com/6535354/88199973-5665dc00-cbfa-11ea-8f62-d8682ce44afe.png)

I guess it worked?

**Comment by muqiaoy** [comment]
Yes, although I didn't find the delete option. Thanks!

**Comment by MohitShridhar** [comment]
Let me check with the AI2 Leaderboard team.

**Comment by MohitShridhar** [comment]
@muqiaoy sorry for the delay. So you don't need to click 'Publish' to see the results. But you have to wait a bit for the evaluation server to finish checking all the test cases. The table will be blank if it's still evaluating.

If you want to delete a published submission, please leaderboard@allenai.org regarding this. Thanks!

**Comment by MohitShridhar** [comment]
Sorry about the confusion. We are coordinating with the leaderboard team to have the option of viewing the results before publishing.

**Comment by sgdgp** [comment]
@MohitShridhar This is my first time using AI2 leaderboard system. Curious to know, if we have the option to view results before publishing what happens to the 1 submission/week restriction. Can we just see results of multiple models and publish the best out of them ?

**Comment by MohitShridhar** [comment]
@sgdgp we are coordinating with AI2's Leaderboard team to enable this feature. It will be updated as soon as possible. Thanks for your patience!

Worst case scenario, I would recommend publishing your results anyway. We can help clean up the leaderboard after the challenge ends :)

**Comment by MohitShridhar** [comment]
You should now be able to preview the results before publishing. If you would like to delete an existing submission, please email leaderboard@allenai.org.
