### ISSUE TITLE
Position and Rotation for objects - requesting clarity as a newbie

### ISSUE THREAD

**Issue by aditya30887** [askforalfred/alfred#41]
Why are there multiple position and rotation values for each object? 

For example knife_8aa9254c in the dataset https://github.com/askforalfred/alfred/blob/master/data/json_2.1.0/train/pick_and_place_simple-Spoon-None-SinkBasin-12/trial_T20190907_035203_361260/traj_data.json

has three position (x,y,z) and rotation values. Which of these three is the initial position of the object? And do the position for the agent and objects use the same (0,0,0)? what is (0,0,0)? 

Thank you for your help! 
-Adi

**Comment by MohitShridhar** [comment]
Hi @aditya30887 these are multiple instances of the same object model. `object_poses` is used to restore the objects in a scene.

**Comment by aditya30887** [comment]
Thanks for your reply. Am I correct in understanding that then each of these instances for a given object can be used as the initial (starting) point for the object?
Am I also correct in my understanding that the initial location of the agent is available in “init_action” under “scene"?

**Comment by MohitShridhar** [comment]
> .. of these instances for a given object can be used as the initial (starting) point for the object

Correct. These are used to restore the scenes in a deterministic manner.   

> Am I also correct in my understanding that the initial location of the agent is available in “init_action” under “scene"

Correct. Calling `init_action` with THOR will place the agent in the starting location of task.

**Comment by MohitShridhar** [comment]
Closing for now.
