### ISSUE TITLE
How much storage space do Resnet Features need?

### ISSUE THREAD

**Issue by LWJ312** [askforalfred/alfred#42]
Hello~ I met some trouble and I need your help.
I have a limited storage space with my PC, so I download json data you offered. I have generated some images and then I want to get Resnet features using extract_resnet.py. But after extracting features in _val_seen_ and _val_unseen_, all the feature.pt files have taken 14.8G，I made an estimation that the _train_ data features may need 200G.
But you offered a 17G data including jsons and features, I don't know how much it takes after unzipping. Maybe it takes less than 200G?
Thanks for your help in advance!

**Comment by MohitShridhar** [comment]
@LWJ312 the unzipped [json_feat_2.1.0](https://ai2-vision-alfred.s3-us-west-2.amazonaws.com/json_feat_2.1.0.7z) folder is ~35GB. It's much smaller because it doesn't contain any generated images.

**Comment by LWJ312** [comment]
@MohitShridhar Thank you~ Yeah, I know what you mean, but now I wonder why my _feature.pt_ files generated following the traj_data.json is much larger than 35GB?

**Comment by MohitShridhar** [comment]
So the generated `feature.pt` contains ResNet features for _every_ frame in the video demonstration. If you turn off `smooth_nav`, it won't save extra frames used to generate smooth-looking videos.

**Comment by LWJ312** [comment]
Oh! I get it. Thank you so much :)
