### ISSUE TITLE
What is the feature processed by?

### ISSUE THREAD

**Issue by cwhao98** [askforalfred/alfred#46]
You provide the processed image feature (`feature_conv.pt`).
But is it processed by resnet18 or maskrcnn-resnet50-fpn?
Thanks.

**Comment by askforalfred** [comment]
Hi Wenhao, as discussed in the paper <https://arxiv.org/pdf/1912.01734.pdf>,
we extract features using Resnet-18 (see Section 4.1 -> Visual Encoding).
However, the extract_resnet.py
<https://github.com/askforalfred/alfred/blob/master/models/utils/extract_resnet.py>
script
currently allows extracting features with either Resnet18 or MaskRCNN.

- Jesse
