### ISSUE TITLE
Fix bugs in the generation code. 

### ISSUE THREAD

**Issue by jiasenlu** [askforalfred/alfred#47]
I found a bug in the generation code, https://github.com/askforalfred/alfred/blob/master/gen/utils/game_util.py#L337

It should be 
`def get_task_str(object_ind, receptacle_ind=None, toggle_ind=None, mrecep_ind=None):
`
instead of 
`def get_task_str(task_type_ind, object_ind, receptacle_ind=None, toggle_ind=None, mrecep_ind=None):
`

**Comment by MohitShridhar** [comment]
Thanks! This is related to this: https://github.com/askforalfred/alfred/issues/31

I'll look at all these in a couple of weeks.

**Comment by MohitShridhar** [comment]
Fixed.
