### ISSUE TITLE
code logic error

### ISSUE THREAD

**Issue by ooodragon94** [askforalfred/alfred#5]
in resnet.py

starting from line 62

```
        if self.model_type == "maskrcnn":
            self.resnet_model = MaskRCNN(args, eval, share_memory, use_conv_feat)
        else:
            self.resnet_model = Resnet18(args, eval, share_memory)
```

this does not make sense.
if you use "maskrcnn" there should be no parameter "use_conv_feat"

whereas the flow of the code does not let the use of maskrcnn at evaluation stage.
this code is quite confusing

**Comment by MohitShridhar** [comment]
Thanks for the pointer! I just pushed a fix. You can pull from master, and let me know if you have any issues?

On a side note: we didn't use MaskRCNN features for any experiments in the paper.
