### ISSUE TITLE
Error：seq2seq_im_mask.py, line125,   keep[d['low_idx']] = im[i]

### ISSUE THREAD

**Issue by shogi880** [askforalfred/alfred#55]
Hi~ I get an Error:

> "MyPC/alfred/models/model/seq2seq_im_mask.py", line 125, in featurize
>     keep[d['low_idx']] = im[i]
> IndexError: index 70 is out of bounds for dimension 0 with size 60

Hi, when I run this script on local macbook. 
`python models/train/train_seq2seq.py --data data/json_feat_2.1.0 --model seq2seq_im_mask --dout exp/model:{model},name:pm_and_subgoals_01 --splits data/splits/oct21.json --batch 8 --pm_aux_loss_wt 0.1 --subgoal_aux_loss_wt 0.1
`

and I fix it to change the code this way. But I don't know is it Okay ~
keep[d['low_idx']] = im[i]
-> keep[d['low_idx']] = im[d['low_idx']]

Could anyone check it for me ! Thank you very much. ^_^

**Comment by MohitShridhar** [comment]
@shogi880 have you pulled the latest from `master`?  Because [L125](https://github.com/askforalfred/alfred/blob/master/models/model/seq2seq_im_mask.py#L125) looks different.

Also, we recently updated the `json_feat_2.1.0` dataset (about a month ago). So make sure to re-download that too.

**Comment by shogi880** [comment]
> @shogi880 have you pulled the latest from `master`? Because [L125](https://github.com/askforalfred/alfred/blob/master/models/model/seq2seq_im_mask.py#L125) looks different.
> 
> Also, we recently updated the `json_feat_2.1.0` dataset (about a month ago). So make sure to re-download that too.

Ohhh! Thanks for your response!
It seems I need to re-download the big data~

By the way, very interesting dataset!! Thanks😊
