### ISSUE TITLE
Bug in evaluation of the GotoLoacation subgoal 

### ISSUE THREAD

**Issue by 594zyc** [askforalfred/alfred#59]
While evaluating the GotoLocation subgoal, the completeness is determined by whether the agent is close enough and the target object of the next subgoal is seen in the last state of the GotoLocation subgoal ([see here](https://github.com/askforalfred/alfred/blob/d12caad32e61c7c6f62901b638bfebdb522a2a7b/env/reward.py#L26)).  However, if in the next subgoal the agent needs to open some nontransparent thing first (e.g. most commonly a fridge) and then pickup/slice/etc the object, the visibility check will fail and the GotoLocation subgoal will be incorrectly classified as unsuccess. To my knowledge this is a bug in the evaluation process. If I misunderstand anything please just ignore this issue. Thank you!

**Comment by MohitShridhar** [comment]
@594zyc this is a bug. The subgoal evaluation numbers for Goto might be slightly higher than reported. I'll take a look at this soon and add an errata. Thanks

**Comment by MohitShridhar** [comment]
Updated the success criteria for `Goto` and added an [errata page](https://github.com/askforalfred/alfred/blob/master/models/ERRATA.md).

**Comment by MohitShridhar** [comment]
Closing for now.
