### ISSUE TITLE
Error in Preprocessing Language

### ISSUE THREAD

**Issue by TheShadow29** [askforalfred/alfred#6]
Hi

I am trying to run the preprocessing steps, but facing an error in `process_language` (https://github.com/askforalfred/alfred/blob/master/data/preprocess.py#L93)

In `train` and `valid` splits, it seems `ridx >= len(ex['turk_annotations']['anns'])` for quite a few annotations. This causes the error in L93.

I am likely missing something here. Any clue as to what is going on? Thank you for your patience.

**Comment by TheShadow29** [comment]
Update: Seems like there is a mis-match between the `full dataset` and `modeling quickstart` provide here: https://github.com/askforalfred/alfred/tree/master/data

It works with `modeling quickstart` data.

**Comment by MohitShridhar** [comment]
Thanks @TheShadow29! There might be some trajectories left over from the generation phase without language annotations. Will check it out soon...

**Comment by MohitShridhar** [comment]
Fixed in the latest [full_2.1.0.zip](https://storage.googleapis.com/alfred_dataset/data/full_2.1.0_v2.zip). Data Readme has been updated.
