### ISSUE TITLE
Does Alfred support multi-agent setting？

### ISSUE THREAD

**Issue by liuxz-cs** [askforalfred/alfred#63]
Is Alfred based on AI2-THOR and what's the difference between Alfred and AI2-THOR？ And does Alfred support the multi-agent setting?

**Comment by MohitShridhar** [comment]
@liuxz-cs ALFRED is a **dataset** based in the AI2THOR **simulator**. ALFRED consists of 25K language annotations for various tasks in AI2THOR. AI2THOR is a simulator that renders the visual and physical interactions. The latest version of AI2THOR supports multi-agent settings, but the ALFRED dataset itself is for single-agent tasks.
