### ISSUE TITLE
error when build docker

### ISSUE THREAD

**Issue by ruinianxu** [askforalfred/alfred#69]
Hi,

I am sorry to bother but I have been stuck for several days since I am new to docker. Really appreciate if anyone can give me some hints. I met the following error when run docker_build.py

```
Step 20/28 : RUN pip install --upgrade pip==19.3.1
 ---> Running in c4096ce64f81
Traceback (most recent call last):
  File "/home/ruinian/alfred_env/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/home/ruinian/alfred_env/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by MohitShridhar** [comment]
@ruinianxu it can be hard to debug this with `docker_build.py`. I would recommend creating an NVIDIA Cuda container from sctatch `docker run --name test1 --runtime -v <alfred_dir>:<alfred_dir_inside_container> nvidia -p 8888:8888 --ipc=host --network=host --privileged -it nvidia/cuda:9.2-devel-ubuntu18.04` and then running the installation commands in the [Dockerfile](https://github.com/askforalfred/alfred/blob/master/Dockerfile#L32) one-line-at-a-time. 

Once you reach `pip install --upgrade pip==19.3.1`, you can try to fix it [by looking it up](https://stackoverflow.com/questions/65896334/python-pip-broken-with-sys-stderr-writeferror-exc/66103179#66103179). Then you can update your Dockerfile and build with `docker_build.py`.

**Comment by Ynjxsjmh** [comment]
See https://github.com/oxwhirl/pymarl/issues/95.
