### ISSUE TITLE
Ground truth predictions don't yield 100% success rate

### ISSUE THREAD

**Issue by shuyanzhou** [askforalfred/alfred#7]
Hi,

I recently find that feeding ground truth actions and masks does not yield a 100% success rate on valid_seen. 

Over 817 valid_seen samples (first 3 removed for personal reason), the result is:
SR: 674/817 = 0.825
PC: 1946/2097 = 0.928

Any thoughts about the possible cause?

**Comment by MohitShridhar** [comment]
Thanks for trying this out @shuyanzhou. Can you email me the results JSON files?

During the data generation, we replayed every trajectory with the masks and GT actions, and evaluated the success rate ([here](https://github.com/askforalfred/alfred/blob/3ac425884b96927b043b90cb431fd0568c8c8da3/gen/scripts/replay_checks.py#L116)). So technically this shouldn't happen.

**Comment by shuyanzhou** [comment]
@MohitShridhar Thanks for your prompt reply! If there is no problem on your side, the difference might come from my own revisions to the code/data. I will check. If I could not solve the problem, I will reopen the issue. Thanks!

**Comment by MohitShridhar** [comment]
Yeah let me how it goes. We put in extra effort during the generation phase to make sure this doesn't happen. We discarded any trajectory that failed the evaluation. But something could have changed since then.

**Comment by MohitShridhar** [comment]
@shuyanzhou looks like there was something faulty in the evaluation metric. Can you please pull from `master` and re-run your GT actions+masks test? Let me know how it goes.

**Comment by shuyanzhou** [comment]
@MohitShridhar thanks for pointing this. I did another evaluation pass, now the results are correct -- GTs yield 100% SR.
