### ISSUE TITLE
Question regarding the ""pddl_params":" of the dataset

### ISSUE THREAD

**Issue by soyeonm** [askforalfred/alfred#75]
Hello,

I have a question regarding the "pddl_params" of the dataset.
e.g.

> "pddl_params": {
>         "mrecep_target": "",
>         "object_sliced": false,
>         "object_target": "Fork",
>         "parent_target": "SinkBasin",
>         "toggle_target": ""
>     },

Are these the ground-truth annotated by a human? Or are these predictions from a model in this paper: https://arxiv.org/pdf/2010.03768.pdf

Thanks!

**Comment by MohitShridhar** [comment]
These are ground-truth params. We sampled these parameters during the dataset generation phase before collecting human annotations.  

**Note:** These params are only available for Train, Val-Seen, Val-Unseen splits, so you can't use them in Test-Seen and Test-Unseen scenes.
