### ISSUE TITLE
Question regarding speed with multiple instances of AI2THOR

### ISSUE THREAD

**Issue by soyeonm** [askforalfred/alfred#77]
Hello,

I have a question regarding the number of threads (the number of instances of AI2THOR's controller).
I saw that in the commands provided in your "models" folder, the "num_threads" are 3. 
e.g.

> $ python models/eval/eval_seq2seq.py --model_path <model_path>/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 3

I observed that on my server, any number of thread (or any simultaneously running instances of AI2THOR) beyond 3 makes the entire computer very, very slow.

Do you have an insight on how to overcome such an issue? Or is this also why the num_threads is "3" for your example command as well?

Thanks all the time.

**Comment by MohitShridhar** [comment]
@soyeonm `num_threads` is the number of parallel instances of THOR to run. The higher the number, the faster the evaluation.  For faster speed you need a machine with more CPUs+RAM.
