### ISSUE TITLE
how can i view the image in traj_data.json file?

### ISSUE THREAD

**Issue by ooodragon94** [askforalfred/alfred#8]
how can i view image named like
"000000000.png"?

**Comment by shuyanzhou** [comment]
You can download the full dataset, all images are included.

**Comment by ooodragon94** [comment]
ah, ok I needed to download the full dataset to view the image, thank you

`$ sh download_data.sh full`

instead of 

`$ sh download_data.sh json_feat`

**Comment by ooodragon94** [comment]
hm.. network is unreachable

> https://storage.googleapis.com/alfred_dataset/data/full_2.1.0.zip

this page isnt loading for some reason..
any idea?

**Comment by shuyanzhou** [comment]
@ooodragon94 Ha, I click the link you provide and it seems like it could be download on my Mac's chrome. I used download_data.sh a few days ago, it also worked for me.
