### ISSUE TITLE
How is the colorSwap image generated？

### ISSUE THREAD

**Issue by Gasoonjia** [askforalfred/alfred#80]
We want to do similar things to original images via AI2thor, but we found out that the simulator (version 2.1.0) does not support such function. 
So may I ask how you swap color for original images? Could you share the image after swapping the color?
Thank you.

**Comment by MohitShridhar** [comment]
@Gasoonjia I believe [MOCA](https://arxiv.org/pdf/2012.03208.pdf) does color-swap augmentation. Maybe check the [repo](https://github.com/gistvision/moca) or ask the MOCA authors on Github?
