### ISSUE TITLE
Could we get the multi-view images from the environment?

### ISSUE THREAD

**Issue by PengkunLiu** [askforalfred/alfred#81]
Sorry to disturb you. We would like to get the multi-view images from the environment for data enhancement.

So may I ask Could we get the multi-view images from the environment of Alfred? 
Thank you. Looking forward to hearing from you.

**Comment by MohitShridhar** [comment]
@PengkunLiu are you referring to panoramic input for a single agent? If so, see [this](https://github.com/askforalfred/alfred/blob/master/doc/FAQ.md#how-do-i-get-panoramic-image-observations).

The simplest way to get any sort of multi-view observations is to navigate with the THOR API and stitch the images yourself.

**Comment by PengkunLiu** [comment]
Thank you very much for your suggestions. I have a further question,  where I should add the 'forceAction = True', because in the function of smooth_rotate, smooth_look, and smooth_move_ahead, I did not find the definition of the 'forceAction'.

**Comment by MohitShridhar** [comment]
@PengkunLiu, `forceAction` should be **True** by default in [`thor_env.py`](https://github.com/askforalfred/alfred/blob/master/env/thor_env.py#L396).
