### ISSUE TITLE
Question on using returned values from "va_interact" for leaderboard submissions

### ISSUE THREAD

**Issue by soyeonm** [askforalfred/alfred#88]
Hello,

In line 583 of "thor_env.py", va_interact returns "target_instance_id". 
Can one use this "target_instance_id" (from the previous step or the current step) as part of input to the model that decides which action to take?
I am asking whether this is allowed or not allowed in the submissions to the leaderboard.

Thank you all the time for your replies.

**Comment by soyeonm** [comment]
Also, "va_interact" uses event.metadata['lastActionSuccess'] inside itself, to decide what to return for "success". Can I use  event.metadata['lastActionSuccess'] inside "step", which is a function called inside "va_interact"? I just want to use it to keep an approximate pose of an agent (not getting the pose from the metadata, but updating an approximate one by myself).

**Comment by MohitShridhar** [comment]
1. No sorry. `va_interact` is only for executing your output. Nothing from that function should be used as _input_ to your model. As stated in the rules “You are only allowed to use **RGB and language instructions** (goal & step-by-step) as _input_ for your agents”.  

2. No sorry. As stated in 1. you can only use RGB and language instructions.
